In [1]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5]) #1d array
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [10]:
#2d array
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [11]:
#3d array
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)


#3D array practise
a4 = np.array([[[1,5,6],
               [8,6,8]],
              [[5,6,5],
               [8,5,2]]])
print(a4)

#2D array practise
a5 = np.array([[1,5,9],
              [5,6,4]])
print(a5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 5 6]
  [8 6 8]]

 [[5 6 5]
  [8 5 2]]]
[[1 5 9]
 [5 6 4]]


Arrange - It creates an array with (start,stop-1,step)

In [15]:
ar1=np.arange(10)
ar=np.arange(2,21)
#ar=np.arange(2,11,2)
print(ar1)
print(ar)


[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Array Multiplication

In [17]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])

y=np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])


In [ ]:
print(x*y) #Normal Multiplication

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [19]:
np.dot(x,y) #matrix multiplication alternative


array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [20]:
x.prod() #element wise multiplication

np.int64(12600)

Every dimension of an array is an axis:
  1D array → only axis=0
  2D array → axis=0 (columns), axis=1 (rows)
  3D array → axis=0 (layers), axis=1 (rows), axis=2 (columns)

In [21]:
x.mean(axis = 1) #average of each row


array([4., 3., 3.])

In [ ]:
print(x.sum()) #sum of all elements
print(x.sum(axis = 0)) #sum of columns
print(x.sum(axis=3)) #not applicable because only used till axis=2 in 3d array

30
[12 12  6]


AxisError: axis 3 is out of bounds for array of dimension 2

In [25]:
print(x.std()) #Standard Deviation 
print(x.var()) #Variance

1.8257418583505538
3.3333333333333335


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50)) #median(50th position)
print(np.percentile(a,25)) #1st quartile (25th position)
print(np.percentile(a,75)) #3rd quartile (75th position) 

5.0
3.0
7.0


In [37]:
b=np.random.randint(11,100, size=(4,4)) #Generates a matrix of random integers with specific size
print(b)


b=np.random.randint(11,100, size=(3,4,4))
print(b)

[[89 41 32 85]
 [41 93 42 78]
 [11 49 56 30]
 [69 26 98 64]]
[[[45 11 49 12]
  [53 43 28 94]
  [36 79 28 37]
  [71 59 11 31]]

 [[74 26 11 41]
  [41 81 31 51]
  [56 53 98 16]
  [71 50 59 47]]

 [[84 89 42 11]
  [52 51 29 19]
  [94 52 99 98]
  [51 56 41 11]]]


Reshape - It reshapes the matrix keeping the elements and the number of elemnts same only changing its size

In [40]:
b=np.random.randint(11,100, size=(4,4))
print(b)

print('2x8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

[[20 44 65 49]
 [67 56 96 26]
 [62 81 83 70]
 [85 83 52 68]]
2x8
[[20 44 65 49 67 56 96 26]
 [62 81 83 70 85 83 52 68]]
8X2
[[20 44]
 [65 49]
 [67 56]
 [96 26]
 [62 81]
 [83 70]
 [85 83]
 [52 68]]


In [ ]:
#Indexing and slicicng in arrays
b=np.random.randint(11,100, size=(4,4))
print(b)


#Acess different elements in a matrix
print(b[0]) #1st row
print(b[0,1]) #1st row 2nd column
print(b[-1]) #last row
print('---------')
print(b[:3]) #1st 3 rows
print('---------') 
print(b[3:]) #last row

[[36 33 64 87]
 [56 54 67 51]
 [16 82 91 33]
 [63 37 43 55]]
[36 33 64 87]
33
[63 37 43 55]
---------
[[36 33 64 87]
 [56 54 67 51]
 [16 82 91 33]]
---------
[[63 37 43 55]]


In [ ]:
.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(a3)a3 = np

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
